### ISSUE TITLE
How do I make it so then it detects language and translates to english

### ISSUE THREAD

**Issue by pikachu1298** [sharplab/deepl4j#22]
Hi, 

I am translating text and am wondering how to make it detect language and translate it to english.
See https://imgur.com/a/OfozQEY
please improve the documentation so I can see how

-pikachu1298

**Comment by ynojima** [comment]
Hi, Thank you for pointing out.
From your feedback, I marked the `source_lang` parameter optional(https://github.com/sharplab/deepl4j/pull/23), and now you can call the `translateText` API without `source_lang` parameter. 
DeepL will detect the source language.


You may test the latest snapshot build from here: https://jitpack.io/#sharplab/deepl4j/master-SNAPSHOT

**Comment by pikachu1298** [comment]
also in my intelllij when i do collections.singletonlist("any text here"), it says that string is required but i provided java.lang.string as a set

**Comment by ynojima** [comment]
Please keep one issue one topic. Please file a new issue with reproducer.
