### ISSUE TITLE
Need help with Collections.singletonlist

### ISSUE THREAD

**Issue by pikachu1298** [sharplab/deepl4j#24]
![image](https://user-images.githubusercontent.com/86435404/179761473-dd67eb42-9617-429f-a5a5-60409fe99ef4.png)

**Comment by ynojima** [comment]
It seems you are calling `translateText` instead of `translateTexts`

**Comment by ynojima** [comment]
And as I wrote in https://github.com/sharplab/deepl4j/issues/22, you need to upgrade the library to `com.github.sharplab:deepl4j:master-SNAPSHOT` to leave `sourceLang` `null` to detect source language.
